namespace ClickIt.Definitions
{
    internal static partial class AltarModsConstants
    {
        #region Downside Modifier Data
        public static readonly IReadOnlyList<(string Id, string Name, string Type, int DefaultValue)> DownsideMods = new List<(string, string, string, int)>
        {
            ("Projectiles are fired in random directions", "Projectiles are fired in random directions", Player, 100),
            ("#% reduced Defences per Frenzy Charge", "(30-50)%% reduced Defences per Frenzy Charge", Player, 100),
            ("#% to Critical Strike Multiplier per Power Charge", "(-40--20)%% to Critical Strike Multiplier per Power Charge", Player, 100),
            ("Non-Damaging Ailments you inflict are reflected back to you", "Non-Damaging Ailments you inflict are reflected back to you", Player, 100),
            ("Curses you inflict are reflected back to you", "Curses you inflict are reflected back to you", Player, 100),
            ("#% reduced Recovery Rate of Life, Mana and Energy Shield per Endurance Charge", "(10-20)%% reduced Recovery Rate of Life, Mana and Energy Shield per Endurance Charge", Player, 80),
            ("Take # Chaos Damage per second during any Flask Effect", "Take 600 Chaos Damage per second during any Flask Effect", Player, 80),
            ("-#% to Chaos Resistance", "(-60--40)%% to Chaos Resistance", Player, 75),
            ("Nearby Enemies Gain #% of their Physical Damage as Extra Chaos Damage", "Nearby Enemies Gain 100%% of their Physical Damage as Extra Chaos Damage", Player, 75),
            ("Gain # Grasping Vines per second while Stationary", "Gain 1 Grasping Vines per second while Stationary", Player, 70),
            ("Gain #% of Physical Damage as Extra Chaos Damage", "Gain (70-130)%% of Physical Damage as Extra Chaos Damage", Boss, 60),
            ("Gain #% of Physical Damage as Extra Chaos Damage", "Gain (70-130)%% of Physical Damage as Extra Chaos Damage", Minion, 60),
            ("-#% to Fire Resistance", "(-60--40)%% to Fire Resistance", Player, 60),
            ("-#% to Cold Resistance", "(-60--40)%% to Cold Resistance", Player, 60),
            ("-#% to Lightning Resistance", "(-60--40)%% to Lightning Resistance", Player, 60),
            ("-#% additional Physical Damage Reduction", "(-60--40)%% additional Physical Damage Reduction", Player, 55),
            ("Gain #% of Physical Damage as Extra Cold Damage", "Gain (50-130)%% of Physical Damage as Extra Cold Damage", Boss, 50),
            ("Gain #% of Physical Damage as Extra Fire Damage", "Gain (50-130)%% of Physical Damage as Extra Fire Damage", Boss, 50),
            ("Gain #% of Physical Damage as Extra Lightning Damage", "Gain (50-80)%% of Physical Damage as Extra Lightning Damage", Boss, 50),
            ("Gain #% of Physical Damage as Extra Cold Damage", "Gain (50-130)%% of Physical Damage as Extra Cold Damage", Minion, 50),
            ("Gain #% of Physical Damage as Extra Fire Damage", "Gain (50-130)%% of Physical Damage as Extra Fire Damage", Minion, 50),
            ("Gain #% of Physical Damage as Extra Lightning Damage", "Gain (50-130)%% of Physical Damage as Extra Lightning Damage", Minion, 50),
            ("Nearby Enemies Gain #% of their Physical Damage as Extra Cold Damage", "Nearby Enemies Gain 100%% of their Physical Damage as Extra Cold Damage", Player, 50),
            ("Nearby Enemies Gain #% of their Physical Damage as Extra Fire Damage", "Nearby Enemies Gain 100%% of their Physical Damage as Extra Fire Damage", Player, 50),
            ("Nearby Enemies Gain #% of their Physical Damage as Extra Lightning Damage", "Nearby Enemies Gain 100%% of their Physical Damage as Extra Lightning Damage", Player, 50),
            ("Gain #% of Physical Damage as Extra Damage of a random Element", "Gain (50-80)%% of Physical Damage as Extra Damage of a random Element", Boss, 45),
            ("Gain #% of Physical Damage as Extra Damage of a random Element", "Gain (50-80)%% of Physical Damage as Extra Damage of a random Element", Minion, 45),
            ("Damage Penetrates #% of Enemy Elemental Resistances", "Damage Penetrates (15-25)%% of Enemy Elemental Resistances", Boss, 45),
            ("-# to Armour", "-3000 to Armour", Player, 45),
            ("-# to Evasion Rating", "-3000 to Evasion Rating", Player, 45),
            ("#% chance to be targeted by a Meteor when you use a Flask", "30%% chance to be targeted by a Meteor when you use a Flask", Player, 40),
            ("Gain #% of Maximum Life as Extra Maximum Energy Shield", "Gain (50-70)%% of Maximum Life as Extra Maximum Energy Shield", Boss, 40),
            ("Hits have #% chance to ignore Enemy Physical Damage Reduction", "Hits have (50-80)%% chance to ignore Enemy Physical Damage Reduction", Minion, 40),
            ("#% additional Physical Damage Reduction", "(50-70)%% additional Physical Damage Reduction", Boss, 35),
            ("#% additional Physical Damage Reduction", "(50-70)%% additional Physical Damage Reduction", Minion, 35),
            ("Inflict Fire, Cold, and Lightning Exposure on Hit", "Inflict Fire, Cold, and Lightning Exposure on Hit", Minion, 35),
            ("+#% to maximum Fire Resistance", "+10%% to maximum Fire Resistance", Boss, 30),
            ("+#% to maximum Cold Resistance", "+10%% to maximum Cold Resistance", Boss, 30),
            ("+#% to maximum Lightning Resistance", "+10%% to maximum Lightning Resistance", Boss, 30),
            ("+#% to maximum Chaos Resistance", "+10%% to maximum Chaos Resistance", Boss, 30),
            ("All Damage taken from Hits can Sap you", "All Damage taken from Hits can Sap you", Player, 30),
            ("All Damage taken from Hits can Scorch you", "All Damage taken from Hits can Scorch you", Player, 30),
            ("+#% to Fire Resistance", "+80%% to Fire Resistance", Boss, 25),
            ("+#% to Cold Resistance", "+80%% to Cold Resistance", Boss, 25),
            ("+#% to Lightning Resistance", "+80%% to Lightning Resistance", Boss, 25),
            ("+#% to Chaos Resistance", "+80%% to Chaos Resistance", Boss, 25),
            ("+#% to Fire Resistance", "+80%% to Fire Resistance", Minion, 25),
            ("+#% to Cold Resistance", "+80%% to Cold Resistance", Minion, 25),
            ("+#% to Lightning Resistance", "+80%% to Lightning Resistance", Minion, 25),
            ("+#% to Chaos Resistance", "+80%% to Chaos Resistance", Minion, 25),
            ("+#% to maximum Fire Resistance", "+10%% to maximum Fire Resistance", Minion, 30),
            ("+#% to maximum Cold Resistance", "+10%% to maximum Cold Resistance", Minion, 30),
            ("+#% to maximum Lightning Resistance", "+10%% to maximum Lightning Resistance", Minion, 30),
            ("+#% to maximum Chaos Resistance", "+10%% to maximum Chaos Resistance", Minion, 30),
            ("#% chance to be Sapped when Hit", "(25-35)%% chance to be Sapped when Hit", Player, 25),
            ("#% chance to be Scorched when Hit", "(25-35)%% chance to be Scorched when Hit", Player, 25),
            ("Skills fire # additional Projectiles", "Skills fire (3-5) additional Projectiles", Minion, 25),
            ("#% increased Flask Charges used", "(20-40)%% increased Flask Charges used", Player, 20),
            ("#% reduced Flask Effect Duration", "(40-60)%% reduced Flask Effect Duration", Player, 20),
            ("All Damage can Ignite", "All Damage can Ignite", Boss, 20),
            ("All Damage can Shock", "All Damage can Shock", Boss, 20),
            ("#% increased Area of Effect", "(70-130)%% increased Area of Effect", Minion, 20),
            ("#% increased Attack Speed", "(30-50)%% increased Attack Speed", Minion, 20),
            ("#% increased Cast Speed", "(30-50)%% increased Cast Speed", Minion, 20),
            ("#% chance for Enemies to drop Chilled Ground when Hitting you, no more than once every 2 seconds", "(25-35)%% chance for Enemies to drop Chilled Ground when Hitting you, no more than once every 2 seconds", Player, 15),
            ("#% chance for Enemies to drop Shocked Ground when Hitting you, no more than once every 2 seconds", "(25-35)%% chance for Enemies to drop Shocked Ground when Hitting you, no more than once every 2 seconds", Player, 15),
            ("All Damage from Hits can Poison", "All Damage from Hits can Poison", Boss, 15),
            ("All Damage with Hits can Chill ", "All Damage with Hits can Chill ", Boss, 15),
            ("Hits always Ignite", "Hits always Ignite", Boss, 15),
            ("Hits always Shock", "Hits always Shock", Boss, 15),
            ("Cover Enemies in Frost on Hit", "Cover Enemies in Frost on Hit", Boss, 15),
            ("Cover Enemies in Ash on Hit", "Cover Enemies in Ash on Hit", Boss, 15),
            ("#% increased Movement Speed", "(30-50)%% increased Movement Speed", Minion, 15),
            ("#% chance to remove a random Charge from Enemy on Hit", "100%% chance to remove a random Charge from Enemy on Hit", Minion, 15),
            ("#% chance for Enemies to drop Burning Ground when Hitting you, no more than once every 2 seconds", "(15-20)%% chance for Enemies to drop Burning Ground when Hitting you, no more than once every 2 seconds", Player, 10),
            ("Poison on Hit", "Poison on Hit", Boss, 10),
            ("+#% chance to Suppress Spell Damage", "+100%% chance to Suppress Spell Damage", Boss, 10),
            ("+#% chance to Suppress Spell Damage", "+100%% chance to Suppress Spell Damage", Minion, 10),
            ("Prevent +#% of Suppressed Spell Damage", "Prevent +(20-30)%% of Suppressed Spell Damage", Boss, 10),
            ("Prevent +#% of Suppressed Spell Damage", "Prevent +(20-30)%% of Suppressed Spell Damage", Minion, 10),
            ("Inflict # Grasping Vine on Hit", "Inflict 1 Grasping Vine on Hit", Minion, 10),
            ("+# to Armour (1600-3200)", "+(1600-3200) to Armour", Minion, 8),
            ("+# to Armour (50000)", "+50000 to Armour", Minion, 8),
            ("+# to Armour (50000)", "+50000 to Armour", Boss, 8),
            ("#% increased Armour", "(100-200)%% increased Armour", Boss, 5),
            ("#% increased Evasion Rating", "(100-200)%% increased Evasion Rating", Boss, 5),
            ("#% increased Evasion Rating", "(250-500)%% increased Evasion Rating", Minion, 5),
            ("#% increased Blind Effect", "(100-200)%% increased Blind Effect", Boss, 5),
            ("Enemies lose # Flask Charges every # seconds and cannot gain Flask Charges for # seconds after being Hit", "Enemies lose 6 Flask Charges every 3 seconds and cannot gain Flask Charges for 6 seconds after being Hit", Boss, 3),
            ("Enemies lose # Flask Charges every # seconds and cannot gain Flask Charges for # seconds after being Hit", "Enemies lose 6 Flask Charges every 3 seconds and cannot gain Flask Charges for 6 seconds after being Hit", Minion, 3),
            ("Drops Burning Ground on Death, lasting # seconds", "Drops Burning Ground on Death, lasting 3 seconds", Minion, 1),
            ("Drops Chilled Ground on Death, lasting # seconds", "Drops Chilled Ground on Death, lasting 3 seconds", Minion, 1),
            ("#% chance to create Shocked Ground on Death, lasting # seconds", "100%% chance to create Shocked Ground on Death, lasting 3 seconds", Minion, 1),
            ("Create Consecrated Ground on Death, lasting # seconds", "Create Consecrated Ground on Death, lasting 6 seconds", Minion, 1),
            ("Create Consecrated Ground on Hit, lasting # seconds", "Create Consecrated Ground on Hit, lasting 6 seconds", Boss, 1),
            ("Nearby Enemies are Hindered, with #% reduced Movement Speed", "Nearby Enemies are Hindered, with 40%% reduced Movement Speed", Boss, 1),
            ("#% Global chance to Blind Enemies on hit", "100%% Global chance to Blind Enemies on hit", Boss, 1),
        };
        #endregion
    }
}
