using System.Collections.Generic;

namespace ClickIt
{
    internal static class AltarModsConstants
    {
        public static Dictionary<string, AffectedTarget> FilterTargetDict { get; } = new Dictionary<string, AffectedTarget> {
            { "Any", AffectedTarget.Any },
            { "Player", AffectedTarget.Player },
            { "Minions", AffectedTarget.Minions },
            { "Boss", AffectedTarget.FinalBoss }
        };
        public static Dictionary<string, AffectedTarget> AltarTargetDict { get; } = new Dictionary<string, AffectedTarget> {
            { "Player gains:", AffectedTarget.Player },
            { "Eldritch Minions gain:", AffectedTarget.Minions },
            { "Map boss gains:", AffectedTarget.FinalBoss }
        };

        public static readonly IReadOnlyList<(string Id, string Name, string Type, int DefaultValue)> DownsideMods = new List<(string, string, string, int)>
        {
            ("+#% to maximum Cold Resistance", "+10%% to maximum Cold Resistance", "Boss", 1),
            ("+#% to Cold Resistance", "+80%% to Cold Resistance", "Boss", 1),
            ("+#% to maximum Lightning Resistance", "+10%% to maximum Lightning Resistance", "Boss", 1),
            ("+#% to Lightning Resistance", "+80%% to Lightning Resistance", "Boss", 1),
            ("#% additional Physical Damage Reduction", "(50–70, 1),%% additional Physical Damage Reduction", "Boss", 1),
            ("All Damage with Hits can Chill", "All Damage with Hits can Chill", "Boss", 1),
            ("Hits always Shock", "Hits always Shock", "Boss", 1),
            ("All Damage can Shock", "All Damage can Shock", "Boss", 1),
            ("Prevent +#% of Suppressed Spell Damage", "Prevent +(20–30, 1),%% of Suppressed Spell Damage", "Boss", 1),
            ("+#% chance to Suppress Spell Damage", "+100%% chance to Suppress Spell Damage", "Boss", 1),
            ("Gain #% of Physical Damage as Extra Damage of a random Element", "Gain (50–80, 1),%% of Physical Damage as Extra Damage of a random Element", "Boss", 1),
            ("Damage Penetrates #% of Enemy Elemental Resistances", "Damage Penetrates (15–25, 1),%% of Enemy Elemental Resistances", "Boss", 1),
            ("Gain #% of Physical Damage as Extra Cold Damage", "Gain (50–80, 1),%% of Physical Damage as Extra Cold Damage", "Boss", 1),
            ("Cover Enemies in Frost on Hit", "Cover Enemies in Frost on Hit", "Boss", 1),
            ("#% Global chance to Blind Enemies on hit", "100%% Global chance to Blind Enemies on hit", "Boss", 1),
            ("#% increased Blind Effect", "(100–200, 1),%% increased Blind Effect", "Boss", 1),
            ("Gain #% of Maximum Life as Extra Maximum Energy Shield", "Gain (50–70, 1),%% of Maximum Life as Extra Maximum Energy Shield", "Boss", 1),
            ("Gain #% of Physical Damage as Extra Cold Damage", "Gain (70–130, 1),%% of Physical Damage as Extra Cold Damage", "Boss", 1),
            ("Gain #% of Physical Damage as Extra Lightning Damage", "Gain (70–130, 1),%% of Physical Damage as Extra Lightning Damage", "Boss", 1),
            ("Eldritch Tentacles", "Eldritch Tentacles", "Boss", 1),
            ("Create Consecrated Ground on Hit, lasting # seconds", "Create Consecrated Ground on Hit, lasting 6 seconds", "Boss", 1),
            ("+#% to maximum Fire Resistance", "+10%% to maximum Fire Resistance", "Boss", 1),
            ("+#% to Fire Resistance", "+80%% to Fire Resistance", "Boss", 1),
            ("+#% to maximum Chaos Resistance", "+10%% to maximum Chaos Resistance", "Boss", 1),
            ("+#% to Chaos Resistance", "+80%% to Chaos Resistance", "Boss", 1),
            ("+# to Armour", "+50000 to Armour", "Boss", 1),
            ("Gain #% of Physical Damage as Extra Fire Damage", "Gain (50–80, 1),%% of Physical Damage as Extra Fire Damage", "Boss", 1),
            ("Cover Enemies in Ash on Hit", "Cover Enemies in Ash on Hit", "Boss", 1),
            ("Hits always Ignite", "Hits always Ignite", "Boss", 1),
            ("All Damage can Ignite", "All Damage can Ignite", "Boss", 1),
            ("Poison on Hit", "Poison on Hit", "Boss", 1),
            ("All Damage from Hits can Poison", "All Damage from Hits can Poison", "Boss", 1),
            ("Enemies lose # Flask Charges every # seconds and cannot gain Flask Charges for # seconds after being Hit", "Enemies lose 6 Flask Charges every 3 seconds and cannot gain Flask Charges for 6 seconds after being Hit", "Boss", 1),
            ("Your hits inflict Malediction", "Your hits inflict Malediction", "Boss", 1),
            ("Gain #% of Physical Damage as Extra Fire Damage", "Gain (70–130, 1),%% of Physical Damage as Extra Fire Damage", "Boss", 1),
            ("Gain #% of Physical Damage as Extra Chaos Damage", "Gain (70–130, 1),%% of Physical Damage as Extra Chaos Damage", "Boss", 1),
            ("#% increased Armour", "(100–200, 1),%% increased Armour", "Boss", 1),
            ("#% increased Evasion Rating", "(100–200, 1),%% increased Evasion Rating", "Boss", 1),
            ("Nearby Enemies are Hindered, with #% reduced Movement Speed", "Nearby Enemies are Hindered, with 40%% reduced Movement Speed", "Boss", 1),
            ("hinder aura behaviour variation [#]", "hinder aura behaviour variation [1]", "Boss", 1),
            ("Hits have #% chance to ignore Enemy Physical Damage Reduction", "Hits have (50–80, 1),%% chance to ignore Enemy Physical Damage Reduction", "Minion", 1),
            ("Skills fire # additional Projectiles", "Skills fire (3–5, 1),additional Projectiles", "Minion", 1),
            ("#% increased Attack Speed", "(30–50, 1),%% increased Attack Speed", "Minion", 1),
            ("#% increased Cast Speed", "(30–50, 1),%% increased Cast Speed", "Minion", 1),
            ("#% increased Movement Speed", "(30–50, 1),%% increased Movement Speed", "Minion", 1),
            ("+#% to maximum Cold Resistance", "+10%% to maximum Cold Resistance", "Minion", 1),
            ("+#% to Cold Resistance", "+80%% to Cold Resistance", "Minion", 1),
            ("+#% to maximum Lightning Resistance", "+10%% to maximum Lightning Resistance", "Minion", 1),
            ("+#% to Lightning Resistance", "+80%% to Lightning Resistance", "Minion", 1),
            ("#% additional Physical Damage Reduction", "(50–80, 1),%% additional Physical Damage Reduction", "Minion", 1),
            ("Prevent +#% of Suppressed Spell Damage", "Prevent +(20–30, 1),%% of Suppressed Spell Damage", "Minion", 1),
            ("+#% chance to Suppress Spell Damage", "+100%% chance to Suppress Spell Damage", "Minion", 1),
            ("#% chance to remove a random Charge from Enemy on Hit", "100%% chance to remove a random Charge from Enemy on Hit", "Minion", 1),
            ("Drops Chilled Ground on Death, lasting # seconds", "Drops Chilled Ground on Death, lasting 3 seconds", "Minion", 1),
            ("#% chance to create Shocked Ground on Death, lasting # seconds", "100%% chance to create Shocked Ground on Death, lasting 3 seconds", "Minion", 1),
            ("Inflict # Grasping Vine on Hit", "Inflict 1 Grasping Vine on Hit", "Minion", 1),
            ("Curse Enemies with Punishment on Hit", "Curse Enemies with Punishment on Hit", "Minion", 1),
            ("Gain #% of Physical Damage as Extra Lightning Damage", "Gain (70–130, 1),%% of Physical Damage as Extra Lightning Damage", "Minion", 1),
            ("Gain #% of Physical Damage as Extra Cold Damage", "Gain (70–130, 1),%% of Physical Damage as Extra Cold Damage", "Minion", 1),
            ("Drops Burning Ground on Death, lasting # seconds", "Drops Burning Ground on Death, lasting 3 seconds", "Minion", 1),
            ("Create Consecrated Ground on Death, lasting # seconds", "Create Consecrated Ground on Death, lasting 6 seconds", "Minion", 1),
            ("Gain #% of Physical Damage as Extra Damage of a random Element", "Gain (70–130, 1),%% of Physical Damage as Extra Damage of a random Element", "Minion", 1),
            ("Inflict Fire, Cold, and Lightning Exposure on Hit", "Inflict Fire, Cold, and Lightning Exposure on Hit", "Minion", 1),
            ("Enemies lose # Flask Charges every # seconds and cannot gain Flask Charges for # seconds after being Hit", "Enemies lose 6 Flask Charges every 3 seconds and cannot gain Flask Charges for 6 seconds after being Hit", "Minion", 1),
            ("+#% to maximum Fire Resistance", "+10%% to maximum Fire Resistance", "Minion", 1),
            ("+#% to Fire Resistance", "+80%% to Fire Resistance", "Minion", 1),
            ("+#% to maximum Chaos Resistance", "+10%% to maximum Chaos Resistance", "Minion", 1),
            ("+#% to Chaos Resistance", "+80%% to Chaos Resistance", "Minion", 1),
            ("+# to Armour", "+50000 to Armour", "Minion", 1),
            ("#% increased Area of Effect", "(70–130, 1),%% increased Area of Effect", "Minion", 1),
            ("#% increased Evasion Rating", "(250–500, 1),%% increased Evasion Rating", "Minion", 1),
            ("Hits always Ignite", "Hits always Ignite", "Minion", 1),
            ("All Damage can Ignite", "All Damage can Ignite", "Minion", 1),
            ("Poison on Hit", "Poison on Hit", "Minion", 1),
            ("All Damage from Hits can Poison", "All Damage from Hits can Poison", "Minion", 1),
            ("Curse Enemies with Vulnerability on Hit", "Curse Enemies with Vulnerability on Hit", "Minion", 1),
            ("Gain #% of Physical Damage as Extra Chaos Damage", "Gain (70–130, 1),%% of Physical Damage as Extra Chaos Damage", "Minion", 1),
            ("Gain #% of Physical Damage as Extra Fire Damage", "Gain (70–130, 1),%% of Physical Damage as Extra Fire Damage", "Minion", 1),
            ("Upside Eldritch Minions gain:", "Upside Eldritch Minions gain:", "Minion", 1),
            ("-#% to Cold Resistance", "(-60–-40, 1),%% to Cold Resistance", "Player", 1),
            ("-#% to Lightning Resistance", "(-60–-40, 1),%% to Lightning Resistance", "Player", 1),
            ("-#% additional Physical Damage Reduction", "(-60–-40, 1),%% additional Physical Damage Reduction", "Player", 1),
            ("#% reduced Defences per Frenzy Charge", "(30–50, 1),%% reduced Defences per Frenzy Charge", "Player", 1),
            ("#% reduced Recovery Rate of Life, Mana and Energy Shield per Endurance Charge", "(10–20, 1),%% reduced Recovery Rate of Life, Mana and Energy Shield per Endurance Charge", "Player", 1),
            ("#% to Critical Strike Multiplier per Power Charge", "(-40–-20, 1),%% to Critical Strike Multiplier per Power Charge", "Player", 1),
            ("#% chance for Enemies to drop Chilled Ground when Hitting you, no more than once every 2 seconds", "(25–35, 1),%% chance for Enemies to drop Chilled Ground when Hitting you, no more than once every 2 seconds", "Player", 1),
            ("#% chance for Enemies to drop Shocked Ground when Hitting you, no more than once every 2 seconds", "(25–35, 1),%% chance for Enemies to drop Shocked Ground when Hitting you, no more than once every 2 seconds", "Player", 1),
            ("All Damage taken from Hits can Sap you", "All Damage taken from Hits can Sap you", "Player", 1),
            ("#% chance to be Sapped when Hit", "(25–35, 1),%% chance to be Sapped when Hit", "Player", 1),
            ("Nearby Enemies Gain #% of their Physical Damage as Extra Cold Damage", "Nearby Enemies Gain 100%% of their Physical Damage as Extra Cold Damage", "Player", 1),
            ("Nearby Enemies Gain #% of their Physical Damage as Extra Lightning Damage", "Nearby Enemies Gain 100%% of their Physical Damage as Extra Lightning Damage", "Player", 1),
            ("Projectiles are fired in random directions", "Projectiles are fired in random directions", "Player", 1),
            ("Spell Hits have #% chance to Hinder you", "Spell Hits have (25–35, 1),%% chance to Hinder you", "Player", 1),
            ("Non-Damaging Ailments you inflict are reflected back to you", "Non-Damaging Ailments you inflict are reflected back to you", "Player", 1),
            ("number of grasping vines to gain every second while stationary [#]", "number of grasping vines to gain every second while stationary [1]", "Player", 1),
            ("-#% to Fire Resistance", "(-60–-40, 1),%% to Fire Resistance", "Player", 1),
            ("-#% to Chaos Resistance", "(-60–-40, 1),%% to Chaos Resistance", "Player", 1),
            ("-# to Armour", "-3000 to Armour", "Player", 1),
            ("-# to Evasion Rating", "-3000 to Evasion Rating", "Player", 1),
            ("#% increased Flask Charges used", "(20–40, 1),%% increased Flask Charges used", "Player", 1),
            ("#% reduced Flask Effect Duration", "(40–60, 1),%% reduced Flask Effect Duration", "Player", 1),
            ("Take # Chaos Damage per second during any Flask Effect", "Take 600 Chaos Damage per second during any Flask Effect", "Player", 1),
            ("Spell Hits have #% chance to Hinder you", "Spell Hits have (20–30, 1),%% chance to Hinder you", "Player", 1),
            ("All Damage taken from Hits can Scorch you", "All Damage taken from Hits can Scorch you", "Player", 1),
            ("#% chance to be Scorched when Hit", "(25–35, 1),%% chance to be Scorched when Hit", "Player", 1),
            ("Curses you inflict are reflected back to you", "Curses you inflict are reflected back to you", "Player", 1),
            ("#% chance for Enemies to drop Burning Ground when Hitting you, no more than once every 2 seconds", "(15–20, 1),%% chance for Enemies to drop Burning Ground when Hitting you, no more than once every 2 seconds", "Player", 1),
            ("#% chance to be targeted by a Meteor when you use a Flask", "30%% chance to be targeted by a Meteor when you use a Flask", "Player", 1),
            ("Nearby Enemies Gain #% of their Physical Damage as Extra Fire Damage", "Nearby Enemies Gain 100%% of their Physical Damage as Extra Fire Damage", "Player", 1),
            ("Nearby Enemies Gain #% of their Physical Damage as Extra Chaos Damage", "Nearby Enemies Gain 100%% of their Physical Damage as Extra Chaos Damage", "Player", 1),

        };

        public static readonly IReadOnlyList<(string Id, string Name, string Type, int DefaultValue)> UpsideMods = new List<(string, string, string, int)>
        {

            ("#% chance to drop an additional Divine Orb", "(1.6–3.2, 1),%% chance to drop an additional Divine Orb", "Minion", 1),
            ("#% chance to drop an additional Exalted Orb", "(1.6–3.2, 1),%% chance to drop an additional Exalted Orb", "Minion", 1),
            ("#% chance to drop an additional Regal Orb", "(1.6–3.2, 1),%% chance to drop an additional Regal Orb", "Minion", 1),
            ("#% chance to drop an additional Lesser Eldritch Ichor", "(1.6–3.2, 1),%% chance to drop an additional Lesser Eldritch Ichor", "Minion", 1),
            ("#% chance to drop an additional Greater Eldritch Ichor", "(1.6–3.2, 1),%% chance to drop an additional Greater Eldritch Ichor", "Minion", 1),
            ("#% chance to drop an additional Grand Eldritch Ichor", "(1.6–3.2, 1),%% chance to drop an additional Grand Eldritch Ichor", "Minion", 1),
            ("#% chance to drop an additional Eldritch Chaos Orb", "(1.6–3.2, 1),%% chance to drop an additional Eldritch Chaos Orb", "Minion", 1),
            ("#% chance to drop an additional Eldritch Exalted Orb", "(1.6–3.2, 1),%% chance to drop an additional Eldritch Exalted Orb", "Minion", 1),
            ("#% chance to drop an additional Eldritch Orb of Annulment", "(1.6–3.2, 1),%% chance to drop an additional Eldritch Orb of Annulment", "Minion", 1),
            ("#% chance to drop an additional Chaos Orb", "(1.6–3.2, 1),%% chance to drop an additional Chaos Orb", "Minion", 1),
            ("#% chance to drop an additional Orb of Alteration", "(1.6–3.2, 1),%% chance to drop an additional Orb of Alteration", "Minion", 1),
            ("#% chance to drop an additional Blessed Orb", "(1.6–3.2, 1),%% chance to drop an additional Blessed Orb", "Minion", 1),
            ("#% chance to drop an additional Orb of Scouring", "(1.6–3.2, 1),%% chance to drop an additional Orb of Scouring", "Minion", 1),
            ("#% chance to drop an additional Chromatic Orb", "(1.6–3.2, 1),%% chance to drop an additional Chromatic Orb", "Minion", 1),
            ("#% chance to drop an additional Orb of Fusing", "(1.6–3.2, 1),%% chance to drop an additional Orb of Fusing", "Minion", 1),
            ("#% chance to drop an additional Jeweller's Orb", "(1.6–3.2, 1),%% chance to drop an additional Jeweller's Orb", "Minion", 1),
            ("#% chance to drop an additional Divination Card which rewards Currency", "(1.6–3.2, 1),%% chance to drop an additional Divination Card which rewards Currency", "Minion", 1),
            ("#% chance to drop an additional Divination Card which rewards Basic Currency", "(1.6–3.2, 1),%% chance to drop an additional Divination Card which rewards Basic Currency", "Minion", 1),
            ("#% chance to drop an additional Divination Card which rewards League Currency", "(1.6–3.2, 1),%% chance to drop an additional Divination Card which rewards League Currency", "Minion", 1),
            ("#% chance to drop an additional Divination Card which rewards other Divination Cards", "(1.6–3.2, 1),%% chance to drop an additional Divination Card which rewards other Divination Cards", "Minion", 1),
            ("#% chance to drop an additional Divination Card which rewards Gems", "(1.6–3.2, 1),%% chance to drop an additional Divination Card which rewards Gems", "Minion", 1),
            ("#% chance to drop an additional Divination Card which rewards Levelled Gems", "(1.6–3.2, 1),%% chance to drop an additional Divination Card which rewards Levelled Gems", "Minion", 1),
            ("#% chance to drop an additional Divination Card which rewards Quality Gems", "(1.6–3.2, 1),%% chance to drop an additional Divination Card which rewards Quality Gems", "Minion", 1),
            ("#% chance to drop an additional Orb of Binding", "(1.6–3.2, 1),%% chance to drop an additional Orb of Binding", "Minion", 1),
            ("#% chance to drop an additional Orb of Horizons", "(1.6–3.2, 1),%% chance to drop an additional Orb of Horizons", "Minion", 1),
            ("#% chance to drop an additional Orb of Unmaking", "(1.6–3.2, 1),%% chance to drop an additional Orb of Unmaking", "Minion", 1),
            ("#% chance to drop an additional Cartographer's Chisel", "(1.6–3.2, 1),%% chance to drop an additional Cartographer's Chisel", "Minion", 1),
            ("#% chance to drop an additional Lesser Eldritch Ember", "(1.6–3.2, 1),%% chance to drop an additional Lesser Eldritch Ember", "Minion", 1),
            ("#% chance to drop an additional Greater Eldritch Ember", "(1.6–3.2, 1),%% chance to drop an additional Greater Eldritch Ember", "Minion", 1),
            ("#% chance to drop an additional Grand Eldritch Ember", "(1.6–3.2, 1),%% chance to drop an additional Grand Eldritch Ember", "Minion", 1),
            ("#% chance to drop an additional Orb of Annulment", "(1.6–3.2, 1),%% chance to drop an additional Orb of Annulment", "Minion", 1),
            ("#% chance to drop an additional Vaal Orb", "(1.6–3.2, 1),%% chance to drop an additional Vaal Orb", "Minion", 1),
            ("#% chance to drop an additional Enkindling Orb", "(1.6–3.2, 1),%% chance to drop an additional Enkindling Orb", "Minion", 1),
            ("#% chance to drop an additional Instilling Orb", "(1.6–3.2, 1),%% chance to drop an additional Instilling Orb", "Minion", 1),
            ("#% chance to drop an additional Orb of Regret", "(1.6–3.2, 1),%% chance to drop an additional Orb of Regret", "Minion", 1),
            ("#% chance to drop an additional Glassblower's Bauble", "(1.6–3.2, 1),%% chance to drop an additional Glassblower's Bauble", "Minion", 1),
            ("#% chance to drop an additional Gemcutter's Prism", "(1.6–3.2, 1),%% chance to drop an additional Gemcutter's Prism", "Minion", 1),
            ("#% chance to drop an additional Divination Card which rewards a Unique Item", "(1.6–3.2, 1),%% chance to drop an additional Divination Card which rewards a Unique Item", "Minion", 1),
            ("#% chance to drop an additional Divination Card which rewards a Unique Weapon", "(1.6–3.2, 1),%% chance to drop an additional Divination Card which rewards a Unique Weapon", "Minion", 1),
            ("#% chance to drop an additional Divination Card which rewards a Unique Armour", "(1.6–3.2, 1),%% chance to drop an additional Divination Card which rewards a Unique Armour", "Minion", 1),
            ("#% chance to drop an additional Divination Card which rewards Unique Jewellery", "(1.6–3.2, 1),%% chance to drop an additional Divination Card which rewards Unique Jewellery", "Minion", 1),
            ("#% chance to drop an additional Divination Card which rewards a Corrupted Unique Item", "(1.6–3.2, 1),%% chance to drop an additional Divination Card which rewards a Corrupted Unique Item", "Minion", 1),
            ("#% chance to drop an additional Divination Card which rewards a Map", "(1.6–3.2, 1),%% chance to drop an additional Divination Card which rewards a Map", "Minion", 1),
            ("#% chance to drop an additional Divination Card which rewards a Unique Map", "(1.6–3.2, 1),%% chance to drop an additional Divination Card which rewards a Unique Map", "Minion", 1),
            ("#% chance to drop an additional Divination Card which rewards a Corrupted Item", "(1.6–3.2, 1),%% chance to drop an additional Divination Card which rewards a Corrupted Item", "Minion", 1),
            ("#% chance to drop an additional Lesser Eldritch Ichor", "(1.2–2.4, 1),%% chance to drop an additional Lesser Eldritch Ichor", "Minion", 1),
            ("#% chance to drop an additional Greater Eldritch Ichor", "(1.2–2.4, 1),%% chance to drop an additional Greater Eldritch Ichor", "Minion", 1),
            ("#% chance to drop an additional Grand Eldritch Ichor", "(1.2–2.4, 1),%% chance to drop an additional Grand Eldritch Ichor", "Minion", 1),
            ("#% chance to drop an additional Lesser Eldritch Ember", "(1.2–2.4, 1),%% chance to drop an additional Lesser Eldritch Ember", "Minion", 1),
            ("#% chance to drop an additional Greater Eldritch Ember", "(1.2–2.4, 1),%% chance to drop an additional Greater Eldritch Ember", "Minion", 1),
            ("#% chance to drop an additional Grand Eldritch Ember", "(1.2–2.4, 1),%% chance to drop an additional Grand Eldritch Ember", "Minion", 1),
            ("#% chance to drop an additional Breach Scarab", "(1.6–3.2, 1),%% chance to drop an additional Breach Scarab", "Minion", 1),
            ("#% chance to drop an additional Delirium Scarab", "(1.6–3.2, 1),%% chance to drop an additional Delirium Scarab", "Minion", 1),
            ("#% chance to drop an additional Legion Scarab", "(1.6–3.2, 1),%% chance to drop an additional Legion Scarab", "Minion", 1),
            ("#% chance to drop an additional Blight Scarab", "(1.6–3.2, 1),%% chance to drop an additional Blight Scarab", "Minion", 1),
            ("#% chance to drop an additional Ritual Scarab", "(1.6–3.2, 1),%% chance to drop an additional Ritual Scarab", "Minion", 1),
            ("#% chance to drop an additional Harvest Scarab", "(1.6–3.2, 1),%% chance to drop an additional Harvest Scarab", "Minion", 1),
            ("#% chance to drop an additional Ultimatum Scarab", "(1.6–3.2, 1),%% chance to drop an additional Ultimatum Scarab", "Minion", 1),
            ("#% chance to drop an additional Abyss Scarab", "(1.6–3.2, 1),%% chance to drop an additional Abyss Scarab", "Minion", 1),
            ("#% chance to drop an additional Expedition Scarab", "(1.6–3.2, 1),%% chance to drop an additional Expedition Scarab", "Minion", 1),
            ("#% chance to drop an additional Betrayal Scarab", "(1.6–3.2, 1),%% chance to drop an additional Betrayal Scarab", "Minion", 1),
            ("#% chance to drop an additional Bestiary Scarab", "(1.6–3.2, 1),%% chance to drop an additional Bestiary Scarab", "Minion", 1),
            ("#% chance to drop an additional Incursion Scarab", "(1.6–3.2, 1),%% chance to drop an additional Incursion Scarab", "Minion", 1),
            ("#% chance to drop an additional Sulphite Scarab", "(1.6–3.2, 1),%% chance to drop an additional Sulphite Scarab", "Minion", 1),
            ("#% chance to drop an additional Influence Scarab", "(1.6–3.2, 1),%% chance to drop an additional Influence Scarab", "Minion", 1),
            ("#% chance to drop an additional Cartography Scarab", "(1.6–3.2, 1),%% chance to drop an additional Cartography Scarab", "Minion", 1),
            ("#% chance to drop an additional Divination Scarab", "(1.6–3.2, 1),%% chance to drop an additional Divination Scarab", "Minion", 1),
            ("#% chance to drop an additional Anarchy Scarab", "(1.6–3.2, 1),%% chance to drop an additional Anarchy Scarab", "Minion", 1),
            ("#% chance to drop an additional Harbinger Scarab", "(1.6–3.2, 1),%% chance to drop an additional Harbinger Scarab", "Minion", 1),
            ("#% chance to drop an additional Miscellaneous Scarab", "(1.6–3.2, 1),%% chance to drop an additional Miscellaneous Scarab", "Minion", 1),
            ("#% chance to drop an additional Beyond Scarab", "(1.6–3.2, 1),%% chance to drop an additional Beyond Scarab", "Minion", 1),
            ("#% chance to drop an additional Torment Scarab", "(1.6–3.2, 1),%% chance to drop an additional Torment Scarab", "Minion", 1),
            ("#% chance to drop an additional Ambush Scarab", "(1.6–3.2, 1),%% chance to drop an additional Ambush Scarab", "Minion", 1),
            ("#% chance to drop an additional Domination Scarab", "(1.6–3.2, 1),%% chance to drop an additional Domination Scarab", "Minion", 1),
            ("#% chance to drop an additional Essence Scarab", "(1.6–3.2, 1),%% chance to drop an additional Essence Scarab", "Minion", 1),
            ("#% chance to drop an additional Reliquary Scarab", "(1.6–3.2, 1),%% chance to drop an additional Reliquary Scarab", "Minion", 1),

            ("Final Boss drops # additional Divine Orbs", "Final Boss drops (2–4, 1),additional Divine Orbs", "Boss", 1),
            ("Final Boss drops # additional Exalted Orbs", "Final Boss drops (2–4, 1),additional Exalted Orbs", "Boss", 1),
            ("Final Boss drops # additional Regal Orbs", "Final Boss drops (2–4, 1),additional Regal Orbs", "Boss", 1),
            ("Final Boss drops # additional Lesser Eldritch Ichors", "Final Boss drops (2–4, 1),additional Lesser Eldritch Ichors", "Boss", 1),
            ("Final Boss drops # additional Greater Eldritch Ichors", "Final Boss drops (2–4, 1),additional Greater Eldritch Ichors", "Boss", 1),
            ("Final Boss drops # additional Grand Eldritch Ichors", "Final Boss drops (2–4, 1),additional Grand Eldritch Ichors", "Boss", 1),
            ("Final Boss drops # additional Eldritch Chaos Orbs", "Final Boss drops (2–4, 1),additional Eldritch Chaos Orbs", "Boss", 1),
            ("Final Boss drops # additional Eldritch Exalted Orbs", "Final Boss drops (2–4, 1),additional Eldritch Exalted Orbs", "Boss", 1),
            ("Final Boss drops # additional Eldritch Orbs of Annulment", "Final Boss drops (2–4, 1),additional Eldritch Orbs of Annulment", "Boss", 1),
            ("Final Boss drops # additional Chaos Orbs", "Final Boss drops (2–4, 1),additional Chaos Orbs", "Boss", 1),
            ("Final Boss drops # additional Orbs of Alteration", "Final Boss drops (2–4, 1),additional Orbs of Alteration", "Boss", 1),
            ("Final Boss drops # additional Blessed Orbs", "Final Boss drops (2–4, 1),additional Blessed Orbs", "Boss", 1),
            ("Final Boss drops # additional Orbs of Scouring", "Final Boss drops (2–4, 1),additional Orbs of Scouring", "Boss", 1),
            ("Final Boss drops # additional Chromatic Orbs", "Final Boss drops (2–4, 1),additional Chromatic Orbs", "Boss", 1),
            ("Final Boss drops # additional Orbs of Fusing", "Final Boss drops (2–4, 1),additional Orbs of Fusing", "Boss", 1),
            ("Final Boss drops # additional Jeweller's Orbs", "Final Boss drops (2–4, 1),additional Jeweller's Orbs", "Boss", 1),
            ("Final Boss drops # additional Divination Cards which reward Currency", "Final Boss drops (2–4, 1),additional Divination Cards which reward Currency", "Boss", 1),
            ("Final Boss drops # additional Divination Cards which reward Basic Currency", "Final Boss drops (2–4, 1),additional Divination Cards which reward Basic Currency", "Boss", 1),
            ("Final Boss drops # additional Divination Cards which reward League Currency", "Final Boss drops (2–4, 1),additional Divination Cards which reward League Currency", "Boss", 1),
            ("Final Boss drops # additional Divination Cards which reward other Divination Cards", "Final Boss drops (2–4, 1),additional Divination Cards which reward other Divination Cards", "Boss", 1),
            ("Final Boss drops # additional Divination Cards which reward Gems", "Final Boss drops (2–4, 1),additional Divination Cards which reward Gems", "Boss", 1),
            ("Final Boss drops # additional Divination Cards which reward Levelled Gems", "Final Boss drops (2–4, 1),additional Divination Cards which reward Levelled Gems", "Boss", 1),
            ("Final Boss drops # additional Divination Cards which reward Quality Gems", "Final Boss drops (2–4, 1),additional Divination Cards which reward Quality Gems", "Boss", 1),
            ("Final Boss drops # additional Orbs of Binding", "Final Boss drops (2–4, 1),additional Orbs of Binding", "Boss", 1),
            ("Final Boss drops # additional Orbs of Horizons", "Final Boss drops (2–4, 1),additional Orbs of Horizons", "Boss", 1),
            ("Final Boss drops # additional Orbs of Unmaking", "Final Boss drops (2–4, 1),additional Orbs of Unmaking", "Boss", 1),
            ("Final Boss drops # additional Cartographer's Chisels", "Final Boss drops (2–4, 1),additional Cartographer's Chisels", "Boss", 1),
            ("Final Boss drops # additional Lesser Eldritch Embers", "Final Boss drops (2–4, 1),additional Lesser Eldritch Embers", "Boss", 1),
            ("Final Boss drops # additional Greater Eldritch Embers", "Final Boss drops (2–4, 1),additional Greater Eldritch Embers", "Boss", 1),
            ("Final Boss drops # additional Grand Eldritch Embers", "Final Boss drops (2–4, 1),additional Grand Eldritch Embers", "Boss", 1),
            ("Final Boss drops # additional Orbs of Annulment", "Final Boss drops (2–4, 1),additional Orbs of Annulment", "Boss", 1),
            ("Final Boss drops # additional Vaal Orbs", "Final Boss drops (2–4, 1),additional Vaal Orbs", "Boss", 1),
            ("Final Boss drops # additional Enkindling Orbs", "Final Boss drops (2–4, 1),additional Enkindling Orbs", "Boss", 1),
            ("Final Boss drops # additional Instilling Orbs", "Final Boss drops (2–4, 1),additional Instilling Orbs", "Boss", 1),
            ("Final Boss drops # additional Orbs of Regret", "Final Boss drops (2–4, 1),additional Orbs of Regret", "Boss", 1),
            ("Final Boss drops # additional Glassblower's Baubles", "Final Boss drops (2–4, 1),additional Glassblower's Baubles", "Boss", 1),
            ("Final Boss drops # additional Gemcutter's Prisms", "Final Boss drops (2–4, 1),additional Gemcutter's Prisms", "Boss", 1),
            ("Final Boss drops # additional Divination Cards which reward a Unique Item", "Final Boss drops (2–4, 1),additional Divination Cards which reward a Unique Item", "Boss", 1),
            ("Final Boss drops # additional Divination Cards which reward a Unique Weapon", "Final Boss drops (2–4, 1),additional Divination Cards which reward a Unique Weapon", "Boss", 1),
            ("Final Boss drops # additional Divination Cards which reward a Unique Armour", "Final Boss drops (2–4, 1),additional Divination Cards which reward a Unique Armour", "Boss", 1),
            ("Final Boss drops # additional Divination Cards which reward Unique Jewellery", "Final Boss drops (2–4, 1),additional Divination Cards which reward Unique Jewellery", "Boss", 1),
            ("Final Boss drops # additional Divination Cards which reward a Corrupted Unique Item", "Final Boss drops (2–4, 1),additional Divination Cards which reward a Corrupted Unique Item", "Boss", 1),
            ("Final Boss drops # additional Divination Cards which reward a Map", "Final Boss drops (2–4, 1),additional Divination Cards which reward a Map", "Boss", 1),
            ("Final Boss drops # additional Divination Cards which reward a Unique Map", "Final Boss drops (2–4, 1),additional Divination Cards which reward a Unique Map", "Boss", 1),
            ("Final Boss drops # additional Divination Cards which reward a Corrupted Item", "Final Boss drops (2–4, 1),additional Divination Cards which reward a Corrupted Item", "Boss", 1),
            ("Final Boss drops # additional Lesser Eldritch Ichor", "Final Boss drops 1 additional Lesser Eldritch Ichor", "Boss", 1),
            ("Final Boss drops # additional Greater Eldritch Ichor", "Final Boss drops 1 additional Greater Eldritch Ichor", "Boss", 1),
            ("Final Boss drops # additional Grand Eldritch Ichor", "Final Boss drops 1 additional Grand Eldritch Ichor", "Boss", 1),
            ("Final Boss drops # additional Lesser Eldritch Ember", "Final Boss drops 1 additional Lesser Eldritch Ember", "Boss", 1),
            ("Final Boss drops # additional Greater Eldritch Ember", "Final Boss drops 1 additional Greater Eldritch Ember", "Boss", 1),
            ("Final Boss drops # additional Grand Eldritch Ember", "Final Boss drops 1 additional Grand Eldritch Ember", "Boss", 1),
            ("Final Boss drops # additional Breach Scarabs", "Final Boss drops (2–4, 1),additional Breach Scarabs", "Boss", 1),
            ("Final Boss drops # additional Delirium Scarabs", "Final Boss drops (2–4, 1),additional Delirium Scarabs", "Boss", 1),
            ("Final Boss drops # additional Legion Scarabs", "Final Boss drops (2–4, 1),additional Legion Scarabs", "Boss", 1),
            ("Final Boss drops # additional Blight Scarabs", "Final Boss drops (2–4, 1),additional Blight Scarabs", "Boss", 1),
            ("Final Boss drops # additional Ritual Scarabs", "Final Boss drops (2–4, 1),additional Ritual Scarabs", "Boss", 1),
            ("Final Boss drops # additional Harvest Scarabs", "Final Boss drops (2–4, 1),additional Harvest Scarabs", "Boss", 1),
            ("Final Boss drops # additional Ultimatum Scarabs", "Final Boss drops (2–4, 1),additional Ultimatum Scarabs", "Boss", 1),
            ("Final Boss drops # additional Abyss Scarabs", "Final Boss drops (2–4, 1),additional Abyss Scarabs", "Boss", 1),
            ("Final Boss drops # additional Expedition Scarabs", "Final Boss drops (2–4, 1),additional Expedition Scarabs", "Boss", 1),
            ("Final Boss drops # additional Betrayal Scarabs", "Final Boss drops (2–4, 1),additional Betrayal Scarabs", "Boss", 1),
            ("Final Boss drops # additional Bestiary Scarabs", "Final Boss drops (2–4, 1),additional Bestiary Scarabs", "Boss", 1),
            ("Final Boss drops # additional Incursion Scarabs", "Final Boss drops (2–4, 1),additional Incursion Scarabs", "Boss", 1),
            ("Final Boss drops # additional Sulphite Scarabs", "Final Boss drops (2–4, 1),additional Sulphite Scarabs", "Boss", 1),
            ("Final Boss drops # additional Influence Scarabs", "Final Boss drops (2–4, 1),additional Influence Scarabs", "Boss", 1),
            ("Final Boss drops # additional Cartography Scarabs", "Final Boss drops (2–4, 1),additional Cartography Scarabs", "Boss", 1),
            ("Final Boss drops # additional Divination Scarabs", "Final Boss drops (2–4, 1),additional Divination Scarabs", "Boss", 1),
            ("Final Boss drops # additional Anarchy Scarabs", "Final Boss drops (2–4, 1),additional Anarchy Scarabs", "Boss", 1),
            ("Final Boss drops # additional Harbinger Scarabs", "Final Boss drops (2–4, 1),additional Harbinger Scarabs", "Boss", 1),
            ("Final Boss drops # additional Miscellaneous Scarabs", "Final Boss drops (2–4, 1),additional Miscellaneous Scarabs", "Boss", 1),
            ("Final Boss drops # additional Beyond Scarabs", "Final Boss drops (2–4, 1),additional Beyond Scarabs", "Boss", 1),
            ("Final Boss drops # additional Torment Scarabs", "Final Boss drops (2–4, 1),additional Torment Scarabs", "Boss", 1),
            ("Final Boss drops # additional Ambush Scarabs", "Final Boss drops (2–4, 1),additional Ambush Scarabs", "Boss", 1),
            ("Final Boss drops # additional Domination Scarabs", "Final Boss drops (2–4, 1),additional Domination Scarabs", "Boss", 1),
            ("Final Boss drops # additional Essence Scarabs", "Final Boss drops (2–4, 1),additional Essence Scarabs", "Boss", 1),
            ("Final Boss drops # additional Reliquary Scarabs", "Final Boss drops (2–4, 1),additional Reliquary Scarabs", "Boss", 1),

            ("Basic Currency Items dropped by slain Enemies have #% chance to be Duplicated", "Basic Currency Items dropped by slain Enemies have (15–30, 1),%% chance to be Duplicated", "Player", 1),
            ("Gems dropped by slain Enemies have #% chance to be Duplicated", "Gems dropped by slain Enemies have (15–30, 1),%% chance to be Duplicated", "Player", 1),
            ("Unique Items dropped by slain Enemies have #% chance to be Duplicated", "Unique Items dropped by slain Enemies have (15–30, 1),%% chance to be Duplicated", "Player", 1),
            ("Scarabs dropped by slain Enemies have #% chance to be Duplicated", "Scarabs dropped by slain Enemies have (15–30, 1),%% chance to be Duplicated", "Player", 1),
            ("Maps dropped by slain Enemies have #% chance to be Duplicated", "Maps dropped by slain Enemies have (15–30, 1),%% chance to be Duplicated", "Player", 1),
            ("Divination Cards dropped by slain Enemies have #% chance to be Duplicated", "Divination Cards dropped by slain Enemies have (15–30, 1),%% chance to be Duplicated", "Player", 1),
            ("#% increased Quantity of Items found in this Area", "(10–20, 1),%% increased Quantity of Items found in this Area", "Player", 1),
            ("#% increased Rarity of Items found in this Area", "(15–35, 1),%% increased Rarity of Items found in this Area", "Player", 1),
            ("Basic Currency Items dropped by slain Enemies have #% chance to be Duplicated", "Basic Currency Items dropped by slain Enemies have (10–15, 1),%% chance to be Duplicated", "Player", 1),
            ("Gems dropped by slain Enemies have #% chance to be Duplicated", "Gems dropped by slain Enemies have (10–15, 1),%% chance to be Duplicated", "Player", 1),
            ("Maps dropped by slain Enemies have #% chance to be Duplicated", "Maps dropped by slain Enemies have (10–15, 1),%% chance to be Duplicated", "Player", 1),
            ("#% increased Quantity of Items found in this Area", "(10–15, 1),%% increased Quantity of Items found in this Area", "Player", 1),
            ("#% increased Rarity of Items found in this Area", "(5–10, 1),%% increased Rarity of Items found in this Area", "Player", 1),
            ("#% increased Experience gain", "(8–12, 1),%% increased Experience gain", "Player", 1),

        };




    }

    public enum AffectedTarget
    {
        Any = 0,
        Player = 1,
        Minions = 2,
        FinalBoss = 3,
    }
    public enum EffectType
    {
        Neutral,
        Upside,
        Downside,
    }



}