global using Altars = global::ClickIt.Features.Altars;
global using Area = global::ClickIt.Features.Area;
global using Click = global::ClickIt.Features.Click;
global using CoreRuntime = global::ClickIt.Core.Runtime;
global using CoreSettings = global::ClickIt.Core.Settings;
global using CoreLifecycle = global::ClickIt.Core.Lifecycle;
global using LabelInventory = global::ClickIt.Features.Labels.Inventory;
global using Labels = global::ClickIt.Features.Labels;
global using LabelSelection = global::ClickIt.Features.Labels.Selection;
global using Mechanics = global::ClickIt.Features.Mechanics;
global using Pathfinding = global::ClickIt.Features.Pathfinding;
global using Policies = global::ClickIt.Features.Labels.Classification.Policies;
global using Shared = global::ClickIt.Shared;
global using TestUtils = global::ClickIt.Tests.TestUtils;
global using UI = global::ClickIt.UI;
global using UISettings = global::ClickIt.UI.Settings;
global using global::ClickIt.Shared;
global using global::ClickIt.UI;
global using global::ClickIt.Core.Settings;
global using global::ClickIt.Core.Lifecycle;
global using global::ClickIt.Core.Settings.Altar;
global using global::ClickIt.Core.Settings.Defaults;
global using global::ClickIt.Core.Settings.Mechanics;
global using global::ClickIt.Core.Settings.Normalization;
global using global::ClickIt.Core.Settings.Runtime;
global using global::ClickIt.Core.Settings.Ultimatum;
global using global::ClickIt.Features.Altars;
global using global::ClickIt.Features.Area;
global using global::ClickIt.Features.Click;
global using global::ClickIt.Features.Click.Core;
global using global::ClickIt.Features.Click.Core.Contracts;
global using global::ClickIt.Features.Click.Runtime;
global using global::ClickIt.Features.Click.State;
global using global::ClickIt.Features.Essence;
global using global::ClickIt.Features.Labels;
global using global::ClickIt.Features.Labels.Application;
global using global::ClickIt.Features.Labels.Classification;
global using global::ClickIt.Features.Labels.Diagnostics;
global using global::ClickIt.Features.Labels.Inventory;
global using global::ClickIt.Features.Labels.Selection;
global using global::ClickIt.Features.Mechanics;
global using global::ClickIt.Features.Pathfinding;
global using global::ClickIt.Features.Shrines;
global using global::ClickIt.Shared.Diagnostics;
global using global::ClickIt.Shared.Game;
global using global::ClickIt.Shared.Input;
global using global::ClickIt.Shared.Math;
global using global::ClickIt.UI.Debug;
global using global::ClickIt.UI.Debug.Layout;
global using global::ClickIt.UI.Debug.Sections;
global using global::ClickIt.UI.Overlays.Altars;
global using global::ClickIt.UI.Overlays.Common;
global using global::ClickIt.UI.Overlays.Inventory;
global using global::ClickIt.UI.Overlays.Pathfinding;
global using global::ClickIt.UI.Overlays.Ultimatum;
global using global::ClickIt.UI.Settings;
global using global::ClickIt.UI.Settings.Panels;
global using MechanicIds = global::ClickIt.Features.Mechanics.MechanicIds;
global using ShrineService = global::ClickIt.Features.Shrines.ShrineService;
global using Shrines = global::ClickIt.Features.Shrines;
global using AlertService = global::ClickIt.Features.Altars.AlertService;
global using AltarMatcher = global::ClickIt.Features.Altars.AltarMatcher;
global using AltarModMatcher = global::ClickIt.Features.Altars.AltarModMatcher;
global using AltarModsConstants = global::ClickIt.Features.Altars.AltarModsConstants;
global using AltarParser = global::ClickIt.Features.Altars.AltarParser;
global using AltarScanner = global::ClickIt.Features.Altars.AltarScanner;
global using AltarService = global::ClickIt.Features.Altars.AltarService;
global using AltarWeights = global::ClickIt.Features.Altars.AltarWeights;
global using AreaService = global::ClickIt.Features.Area.AreaService;
global using ChestLootSettlementTiming = global::ClickIt.Features.Click.ChestLootSettlementTiming;
global using ChestLootSettlementTimingOptions = global::ClickIt.Features.Click.ChestLootSettlementTimingOptions;
global using ClickService = global::ClickIt.Features.Click.ClickAutomationPort;
global using ClickSettings = global::ClickIt.Features.Labels.ClickSettings;
global using Constants = global::ClickIt.Shared.Game.Constants;
global using EssenceService = global::ClickIt.Features.Essence.EssenceService;
global using IElementAdapter = global::ClickIt.Shared.Game.IElementAdapter;
global using ItemCategoryCatalog = global::ClickIt.Features.Labels.Inventory.ItemCategoryCatalog;
global using ItemCategoryDefinition = global::ClickIt.Features.Labels.Inventory.ItemCategoryDefinition;
global using ItemListKind = global::ClickIt.Features.Labels.Inventory.ItemListKind;
global using LabelFilterService = global::ClickIt.Features.Labels.LabelFilterPort;
global using LostShipmentCandidate = global::ClickIt.Features.Click.State.LostShipmentCandidate;
global using MechanicRank = global::ClickIt.Features.Click.State.MechanicRank;
global using PathfindingService = global::ClickIt.Features.Pathfinding.PathfindingService;
global using SettlersOreCandidate = global::ClickIt.Features.Click.State.SettlersOreCandidate;
global using UltimatumModifiersConstants = global::ClickIt.Features.Mechanics.UltimatumModifiersConstants;
global using VisibleMechanicCacheState = global::ClickIt.Features.Click.State.VisibleMechanicCacheState;
global using WeightCalculator = global::ClickIt.Features.Altars.WeightCalculator;
global using WeightTypeConstants = global::ClickIt.Shared.Game.WeightTypeConstants;