#pragma warning disable IDE0005

global using ImGuiNET;
global using Microsoft.CSharp.RuntimeBinder;
global using Newtonsoft.Json;
global using SharpDX;
global using System;
global using System.Buffers;
global using System.Collections;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.IO;
global using System.Linq;
global using System.Net.Http;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Runtime.Serialization;
global using System.Runtime.Versioning;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Windows.Forms;

global using ClickIt;
global using ClickIt.Core;
global using ClickIt.Core.Bootstrap;
global using ClickIt.Core.Lifecycle;
global using ClickIt.Core.Runtime;
global using ClickIt.Core.Settings;
global using ClickIt.Core.Settings.Altar;
global using ClickIt.Core.Settings.Defaults;
global using ClickIt.Core.Settings.Mechanics;
global using ClickIt.Core.Settings.Normalization;
global using ClickIt.Core.Settings.Runtime;
global using ClickIt.Core.Settings.Ultimatum;
global using ClickIt.Features;
global using ClickIt.Features.Altars;
global using ClickIt.Features.Area;
global using ClickIt.Features.Area.Runtime;
global using ClickIt.Features.Blight;
global using ClickIt.Features.Blight.Data;
global using ClickIt.Features.Blight.Debug;
global using ClickIt.Features.Blight.Planning;
global using ClickIt.Features.Blight.Strategy;
global using ClickIt.Features.Click;
global using ClickIt.Features.Click.Application;
global using ClickIt.Features.Click.Core;
global using ClickIt.Features.Click.Interaction;
global using ClickIt.Features.Click.Label;
global using ClickIt.Features.Click.Ranking;
global using ClickIt.Features.Click.Runtime;
global using ClickIt.Features.Click.Runtime.TestSeams;
global using ClickIt.Features.Click.Safety;
global using ClickIt.Features.Click.Selection;
global using ClickIt.Features.Click.State;
global using ClickIt.Features.Essence;
global using ClickIt.Features.Harvest;
global using ClickIt.Features.Labels;
global using ClickIt.Features.Labels.Application;
global using ClickIt.Features.Labels.Classification;
global using ClickIt.Features.Labels.Classification.Policies;
global using ClickIt.Features.Labels.Diagnostics;
global using ClickIt.Features.Labels.Inventory;
global using ClickIt.Features.Labels.Inventory.Composition;
global using ClickIt.Features.Labels.Selection;
global using ClickIt.Features.Mechanics;
global using ClickIt.Features.Mechanics.Rules;
global using ClickIt.Features.Observability;
global using ClickIt.Features.Observability.Performance;
global using ClickIt.Features.Observability.TelemetryProjection;
global using ClickIt.Features.Pathfinding;
global using ClickIt.Features.Pathfinding.Diagnostics;
global using ClickIt.Features.Pathfinding.Grid;
global using ClickIt.Features.Pathfinding.Projection;
global using ClickIt.Features.Pathfinding.Runtime;
global using ClickIt.Features.Pathfinding.Terrain;
global using ClickIt.Features.Shrines;
global using ClickIt.Features.Strongboxes;
global using ClickIt.Properties;
global using ClickIt.Shared;
global using ClickIt.Shared.Diagnostics;
global using ClickIt.Shared.Diagnostics.ElementTree;
global using ClickIt.Shared.Game;
global using ClickIt.Shared.Input;
global using ClickIt.Shared.Math;
global using ClickIt.Shared.Rendering;
global using ClickIt.UI;
global using ClickIt.UI.Debug;
global using ClickIt.UI.Debug.Introspection;
global using ClickIt.UI.Debug.Layout;
global using ClickIt.UI.Settings;
global using ClickIt.UI.Settings.Panels;

global using ExileCore;
global using ExileCore.PoEMemory;
global using ExileCore.PoEMemory.Components;
global using ExileCore.PoEMemory.Elements;
global using ExileCore.PoEMemory.Elements.AtlasElements;
global using ExileCore.PoEMemory.Elements.ExpeditionElements;
global using ExileCore.PoEMemory.Elements.InventoryElements;
global using ExileCore.PoEMemory.Elements.Necropolis;
global using ExileCore.PoEMemory.Elements.Sanctum;
global using ExileCore.PoEMemory.Elements.Village;
global using ExileCore.PoEMemory.FilesInMemory;
global using ExileCore.PoEMemory.FilesInMemory.Ancestor;
global using ExileCore.PoEMemory.FilesInMemory.Archnemesis;
global using ExileCore.PoEMemory.FilesInMemory.Atlas;
global using ExileCore.PoEMemory.FilesInMemory.Harvest;
global using ExileCore.PoEMemory.FilesInMemory.Labyrinth;
global using ExileCore.PoEMemory.FilesInMemory.Metamorph;
global using ExileCore.PoEMemory.FilesInMemory.Sanctum;
global using ExileCore.PoEMemory.FilesInMemory.Ultimatum;
global using ExileCore.PoEMemory.FilesInMemory.Village;
global using ExileCore.PoEMemory.MemoryObjects;
global using ExileCore.PoEMemory.MemoryObjects.Ancestor;
global using ExileCore.PoEMemory.MemoryObjects.Heist;
global using ExileCore.PoEMemory.MemoryObjects.Metamorph;
global using ExileCore.PoEMemory.Models;
global using ExileCore.RenderQ;
global using ExileCore.Shared;
global using ExileCore.Shared.AtlasHelper;
global using ExileCore.Shared.Attributes;
global using ExileCore.Shared.Cache;
global using ExileCore.Shared.Enums;
global using ExileCore.Shared.Helpers;
global using ExileCore.Shared.Helpers.MoreLinq;
global using ExileCore.Shared.Interfaces;
global using ExileCore.Shared.Nodes;
global using ExileCore.Shared.Static;
global using GameOffsets;
global using GameOffsets.Components;
global using GameOffsets.Native;
global using GameOffsets.Objects;
global using ProcessMemoryUtilities;
global using ProcessMemoryUtilities.Internal;
global using ProcessMemoryUtilities.Managed;
global using ProcessMemoryUtilities.Native;

global using Altars = ClickIt.Features.Altars;
global using Area = ClickIt.Features.Area;
global using Click = ClickIt.Features.Click;
global using Labels = ClickIt.Features.Labels;
global using Policies = ClickIt.Features.Labels.Classification.Policies;
global using Mechanics = ClickIt.Features.Mechanics;
global using Pathfinding = ClickIt.Features.Pathfinding;
global using Shrines = ClickIt.Features.Shrines;
global using UI = ClickIt.UI;

global using AlertService = ClickIt.Features.Altars.AlertService;
global using AltarMatcher = ClickIt.Features.Altars.AltarMatcher;
global using AltarModMatcher = ClickIt.Features.Altars.AltarModMatcher;
global using AltarModsConstants = ClickIt.Features.Altars.AltarModsConstants;
global using AltarParser = ClickIt.Features.Altars.AltarParser;
global using AltarScanner = ClickIt.Features.Altars.AltarScanner;
global using AltarService = ClickIt.Features.Altars.AltarService;
global using AltarWeights = ClickIt.Features.Altars.AltarWeights;
global using AreaService = ClickIt.Features.Area.AreaService;
global using ChestLootSettlementTiming = ClickIt.Features.Click.Runtime.ChestLootSettlementTiming;
global using ChestLootSettlementTimingOptions = ClickIt.Features.Click.Runtime.ChestLootSettlementTimingOptions;
global using ClickSettings = ClickIt.Features.Labels.ClickSettings;
global using Color = SharpDX.Color;
global using Constants = ClickIt.Shared.Game.Constants;
global using DynamicAccess = ClickIt.Shared.Game.DynamicAccess;
global using DynamicAccessStats = ClickIt.Shared.Game.DynamicAccessStats;
global using ElementAdapter = ClickIt.Shared.Game.ElementAdapter;
global using EntityQueryService = ClickIt.Shared.Game.EntityQueryService;
global using EssenceService = ClickIt.Features.Essence.EssenceService;
global using ExileCoreApi = ExileCore.Core;
global using ExileCoreCoreSettings = ExileCore.CoreSettings;
global using Graphics = ExileCore.Graphics;
global using IElementAdapter = ClickIt.Shared.Game.IElementAdapter;
global using ILabelInteractionPort = ClickIt.Features.Labels.ILabelInteractionPort;
global using ItemCategoryCatalog = ClickIt.Features.Labels.Inventory.ItemCategoryCatalog;
global using ItemCategoryDefinition = ClickIt.Features.Labels.Inventory.ItemCategoryDefinition;
global using ItemListKind = ClickIt.Features.Labels.Inventory.ItemListKind;
global using LockManager = ClickIt.Shared.Input.LockManager;
global using LostShipmentCandidate = ClickIt.Features.Click.State.LostShipmentCandidate;
global using MechanicIds = ClickIt.Features.Mechanics.MechanicIds;
global using MechanicRank = ClickIt.Features.Click.State.MechanicRank;
global using NumVector2 = System.Numerics.Vector2;
global using PathfindingService = ClickIt.Features.Pathfinding.PathfindingService;
global using PluginDelveFlarePolicy = ClickIt.Core.Runtime.PluginDelveFlarePolicy;
global using RectangleF = SharpDX.RectangleF;
global using RuntimeObjectIntrospection = ClickIt.UI.Debug.Introspection.RuntimeObjectIntrospection;
global using RuntimeObjectIntrospectionOptions = ClickIt.UI.Debug.Introspection.RuntimeObjectIntrospectionOptions;
global using SettlersOreCandidate = ClickIt.Features.Click.State.SettlersOreCandidate;
global using ShrineService = ClickIt.Features.Shrines.ShrineService;
global using StackComponent = ExileCore.PoEMemory.Components.Stack;
global using SystemDrawingPoint = System.Drawing.Point;
global using SystemMath = System.Math;
global using UltimatumModifiersConstants = ClickIt.Features.Mechanics.UltimatumModifiersConstants;
global using Vector2 = SharpDX.Vector2;
global using Vector4 = System.Numerics.Vector4;
global using VisibleMechanicCacheState = ClickIt.Features.Click.State.VisibleMechanicCacheState;
global using WeightCalculator = ClickIt.Features.Altars.WeightCalculator;
global using WeightTypeConstants = ClickIt.Shared.Game.WeightTypeConstants;

global using Bootstrap = ClickIt.Core.Bootstrap;
global using Lifecycle = ClickIt.Core.Lifecycle;
global using CoreRuntime = ClickIt.Core.Runtime;
global using CoreSettings = ClickIt.Core.Settings;
global using SettingsAltar = ClickIt.Core.Settings.Altar;
global using SettingsDefaults = ClickIt.Core.Settings.Defaults;
global using SettingsMechanics = ClickIt.Core.Settings.Mechanics;
global using SettingsNormalization = ClickIt.Core.Settings.Normalization;
global using SettingsRuntime = ClickIt.Core.Settings.Runtime;
global using SettingsUltimatum = ClickIt.Core.Settings.Ultimatum;
global using AreaRuntime = ClickIt.Features.Area.Runtime;
global using ClickApplication = ClickIt.Features.Click.Application;
global using ClickCore = ClickIt.Features.Click.Core;
global using ClickInteraction = ClickIt.Features.Click.Interaction;
global using ClickLabel = ClickIt.Features.Click.Label;
global using ClickRanking = ClickIt.Features.Click.Ranking;
global using ClickRuntime = ClickIt.Features.Click.Runtime;
global using TestSeams = ClickIt.Features.Click.Runtime.TestSeams;
global using ClickSafety = ClickIt.Features.Click.Safety;
global using ClickSelection = ClickIt.Features.Click.Selection;
global using ClickState = ClickIt.Features.Click.State;
global using Essence = ClickIt.Features.Essence;
global using LabelApplication = ClickIt.Features.Labels.Application;
global using LabelClassification = ClickIt.Features.Labels.Classification;
global using LabelDiagnostics = ClickIt.Features.Labels.Diagnostics;
global using LabelInventory = ClickIt.Features.Labels.Inventory;
global using InventoryComposition = ClickIt.Features.Labels.Inventory.Composition;
global using LabelSelection = ClickIt.Features.Labels.Selection;
global using MechanicsRules = ClickIt.Features.Mechanics.Rules;
global using Observability = ClickIt.Features.Observability;
global using ObservabilityPerformance = ClickIt.Features.Observability.Performance;
global using ObservabilityTelemetryProjection = ClickIt.Features.Observability.TelemetryProjection;
global using PathfindingDiagnostics = ClickIt.Features.Pathfinding.Diagnostics;
global using PathfindingGrid = ClickIt.Features.Pathfinding.Grid;
global using PathfindingProjection = ClickIt.Features.Pathfinding.Projection;
global using PathfindingRuntime = ClickIt.Features.Pathfinding.Runtime;
global using PathfindingTerrain = ClickIt.Features.Pathfinding.Terrain;
global using Utils = ClickIt.Shared;
global using SharedDiagnostics = ClickIt.Shared.Diagnostics;
global using SharedGame = ClickIt.Shared.Game;
global using SharedInput = ClickIt.Shared.Input;
global using SharedMath = ClickIt.Shared.Math;
global using UIDebug = ClickIt.UI.Debug;
global using UIDebugIntrospection = ClickIt.UI.Debug.Introspection;
global using UISettings = ClickIt.UI.Settings;
global using UISettingsPanels = ClickIt.UI.Settings.Panels;

global using PoEMemory = ExileCore.PoEMemory;
global using PoEComponents = ExileCore.PoEMemory.Components;
global using PoEElements = ExileCore.PoEMemory.Elements;
global using AtlasElements = ExileCore.PoEMemory.Elements.AtlasElements;
global using ExpeditionElements = ExileCore.PoEMemory.Elements.ExpeditionElements;
global using InventoryElements = ExileCore.PoEMemory.Elements.InventoryElements;
global using Necropolis = ExileCore.PoEMemory.Elements.Necropolis;
global using Sanctum = ExileCore.PoEMemory.Elements.Sanctum;
global using Village = ExileCore.PoEMemory.Elements.Village;
global using FilesInMemory = ExileCore.PoEMemory.FilesInMemory;
global using AncestorFiles = ExileCore.PoEMemory.FilesInMemory.Ancestor;
global using ArchnemesisFiles = ExileCore.PoEMemory.FilesInMemory.Archnemesis;
global using AtlasFiles = ExileCore.PoEMemory.FilesInMemory.Atlas;
global using HarvestFiles = ExileCore.PoEMemory.FilesInMemory.Harvest;
global using LabyrinthFiles = ExileCore.PoEMemory.FilesInMemory.Labyrinth;
global using MetamorphFiles = ExileCore.PoEMemory.FilesInMemory.Metamorph;
global using SanctumFiles = ExileCore.PoEMemory.FilesInMemory.Sanctum;
global using UltimatumFiles = ExileCore.PoEMemory.FilesInMemory.Ultimatum;
global using VillageFiles = ExileCore.PoEMemory.FilesInMemory.Village;
global using MemoryObjects = ExileCore.PoEMemory.MemoryObjects;
global using AncestorObjects = ExileCore.PoEMemory.MemoryObjects.Ancestor;
global using HeistObjects = ExileCore.PoEMemory.MemoryObjects.Heist;
global using MetamorphObjects = ExileCore.PoEMemory.MemoryObjects.Metamorph;
global using PoeModels = ExileCore.PoEMemory.Models;
global using RenderQ = ExileCore.RenderQ;
global using ExileCoreShared = ExileCore.Shared;
global using AtlasHelper = ExileCore.Shared.AtlasHelper;
global using ExileAttributes = ExileCore.Shared.Attributes;
global using ExileCache = ExileCore.Shared.Cache;
global using ExileEnums = ExileCore.Shared.Enums;
global using ExileHelpers = ExileCore.Shared.Helpers;
global using MoreLinq = ExileCore.Shared.Helpers.MoreLinq;
global using ExileInterfaces = ExileCore.Shared.Interfaces;
global using ExileNodes = ExileCore.Shared.Nodes;
global using ExileStatic = ExileCore.Shared.Static;

global using OffsetsComponents = GameOffsets.Components;
global using NativeOffsets = GameOffsets.Native;
global using OffsetsObjects = GameOffsets.Objects;
global using PMUInternal = ProcessMemoryUtilities.Internal;
global using PMUManaged = ProcessMemoryUtilities.Managed;
global using PMUNative = ProcessMemoryUtilities.Native;