namespace ClickIt.Features.Altars
{
    internal static partial class AltarModsConstants
    {
        #region Upside Modifier Data
        public static readonly IReadOnlyList<(string Id, string Name, string Type, int DefaultValue)> UpsideMods = new List<(string, string, string, int)>
        {
            ("#% chance to drop an additional Divine Orb", "(1.6-3.2)%% chance to drop an additional Divine Orb", Minion, 100),
            ("#% chance to drop an additional Ancient Orb", "(1.6-3.2)%% chance to drop an additional Ancient Orb", Minion, 75),
            ("#% chance to drop an additional Exalted Orb", "(1.6-3.2)%% chance to drop an additional Exalted Orb", Minion, 50),
            ("#% chance to drop an additional Chaos Orb", "(1.6-3.2)%% chance to drop an additional Chaos Orb", Minion, 20),
            ("#% chance to drop an additional Orb of Annulment", "(1.6-3.2)%% chance to drop an additional Orb of Annulment", Minion, 35),
            ("#% chance to drop an additional Vaal Orb", "(1.6-3.2)%% chance to drop an additional Vaal Orb", Minion, 25),
            ("#% chance to drop an additional Regal Orb", "(1.6-3.2)%% chance to drop an additional Regal Orb", Minion, 15),
            ("#% chance to drop an additional Gemcutter's Prism", "(1.6-3.2)%% chance to drop an additional Gemcutter's Prism", Minion, 18),
            ("#% chance to drop an additional Grand Eldritch Ichor", "(1.6-3.2)%% chance to drop an additional Grand Eldritch Ichor", Minion, 40),
            ("#% chance to drop an additional Greater Eldritch Ichor", "(1.6-3.2)%% chance to drop an additional Greater Eldritch Ichor", Minion, 20),
            ("#% chance to drop an additional Lesser Eldritch Ichor", "(1.6-3.2)%% chance to drop an additional Lesser Eldritch Ichor", Minion, 8),
            ("#% chance to drop an additional Grand Eldritch Ember", "(1.6-3.2)%% chance to drop an additional Grand Eldritch Ember", Minion, 40),
            ("#% chance to drop an additional Greater Eldritch Ember", "(1.6-3.2)%% chance to drop an additional Greater Eldritch Ember", Minion, 20),
            ("#% chance to drop an additional Lesser Eldritch Ember", "(1.6-3.2)%% chance to drop an additional Lesser Eldritch Ember", Minion, 8),
            ("#% chance to drop an additional Eldritch Exalted Orb", "(1.6-3.2)%% chance to drop an additional Eldritch Exalted Orb", Minion, 45),
            ("#% chance to drop an additional Eldritch Chaos Orb", "(1.6-3.2)%% chance to drop an additional Eldritch Chaos Orb", Minion, 15),
            ("#% chance to drop an additional Eldritch Orb of Annulment", "(1.6-3.2)%% chance to drop an additional Eldritch Orb of Annulment", Minion, 38),
            ("#% chance to drop an additional Orb of Fusing", "(1.6-3.2)%% chance to drop an additional Orb of Fusing", Minion, 10),
            ("#% chance to drop an additional Cartographer's Chisel", "(1.6-3.2)%% chance to drop an additional Cartographer's Chisel", Minion, 8),
            ("#% chance to drop an additional Orb of Scouring", "(1.6-3.2)%% chance to drop an additional Orb of Scouring", Minion, 6),
            ("#% chance to drop an additional Jeweller's Orb", "(1.6-3.2)%% chance to drop an additional Jeweller's Orb", Minion, 5),
            ("#% chance to drop an additional Chromatic Orb", "(1.6-3.2)%% chance to drop an additional Chromatic Orb", Minion, 4),
            ("#% chance to drop an additional Orb of Binding", "(1.6-3.2)%% chance to drop an additional Orb of Binding", Minion, 5),
            ("#% chance to drop an additional Orb of Horizons", "(1.6-3.2)%% chance to drop an additional Orb of Horizons", Minion, 6),
            ("#% chance to drop an additional Blessed Orb", "(1.6-3.2)%% chance to drop an additional Blessed Orb", Minion, 3),
            ("#% chance to drop an additional Orb of Regret", "(1.6-3.2)%% chance to drop an additional Orb of Regret", Minion, 8),
            ("#% chance to drop an additional Orb of Unmaking", "(1.6-3.2)%% chance to drop an additional Orb of Unmaking", Minion, 5),
            ("#% chance to drop an additional Glassblower's Bauble", "(1.6-3.2)%% chance to drop an additional Glassblower's Bauble", Minion, 3),
            ("#% chance to drop an additional Enkindling Orb", "(1.6-3.2)%% chance to drop an additional Enkindling Orb", Minion, 4),
            ("#% chance to drop an additional Instilling Orb", "(1.6-3.2)%% chance to drop an additional Instilling Orb", Minion, 4),
            ("#% chance to drop an additional Orb of Alteration", "(1.6-3.2)%% chance to drop an additional Orb of Alteration", Minion, 2),
            ("#% chance to drop an additional Blight Scarab", "(1.6-3.2)%% chance to drop an additional Blight Scarab", Minion, 22),
            ("#% chance to drop an additional Titanic Scarab", "(1.6-3.2)%% chance to drop an additional Titanic Scarab", Minion, 15),
            ("#% chance to drop an additional Kalguuran Scarab", "(1.6-3.2)%% chance to drop an additional Kalguuran Scarab", Minion, 23),
            ("#% chance to drop an additional Delirium Scarab", "(1.6-3.2)%% chance to drop an additional Delirium Scarab", Minion, 22),
            ("#% chance to drop an additional Breach Scarab", "(1.6-3.2)%% chance to drop an additional Breach Scarab", Minion, 25),
            ("#% chance to drop an additional Legion Scarab", "(1.6-3.2)%% chance to drop an additional Legion Scarab", Minion, 26),
            ("#% chance to drop an additional Expedition Scarab", "(1.6-3.2)%% chance to drop an additional Expedition Scarab", Minion, 22),
            ("#% chance to drop an additional Harvest Scarab", "(1.6-3.2)%% chance to drop an additional Harvest Scarab", Minion, 22),
            ("#% chance to drop an additional Ultimatum Scarab", "(1.6-3.2)%% chance to drop an additional Ultimatum Scarab", Minion, 23),
            ("#% chance to drop an additional Betrayal Scarab", "(1.6-3.2)%% chance to drop an additional Betrayal Scarab", Minion, 23),
            ("#% chance to drop an additional Ritual Scarab", "(1.6-3.2)%% chance to drop an additional Ritual Scarab", Minion, 20),
            ("#% chance to drop an additional Abyss Scarab", "(1.6-3.2)%% chance to drop an additional Abyss Scarab", Minion, 22),
            ("#% chance to drop an additional Bestiary Scarab", "(1.6-3.2)%% chance to drop an additional Bestiary Scarab", Minion, 22),
            ("#% chance to drop an additional Incursion Scarab", "(1.6-3.2)%% chance to drop an additional Incursion Scarab", Minion, 23),
            ("#% chance to drop an additional Harbinger Scarab", "(1.6-3.2)%% chance to drop an additional Harbinger Scarab", Minion, 18),
            ("#% chance to drop an additional Sulphite Scarab", "(1.6-3.2)%% chance to drop an additional Sulphite Scarab", Minion, 22),
            ("#% chance to drop an additional Influence Scarab", "(1.6-3.2)%% chance to drop an additional Influence Scarab", Minion, 20),
            ("#% chance to drop an additional Cartography Scarab", "(1.6-3.2)%% chance to drop an additional Cartography Scarab", Minion, 22),
            ("#% chance to drop an additional Divination Scarab", "(1.6-3.2)%% chance to drop an additional Divination Scarab", Minion, 30),
            ("#% chance to drop an additional Essence Scarab", "(1.6-3.2)%% chance to drop an additional Essence Scarab", Minion, 18),
            ("#% chance to drop an additional Beyond Scarab", "(1.6-3.2)%% chance to drop an additional Beyond Scarab", Minion, 22),
            ("#% chance to drop an additional Anarchy Scarab", "(1.6-3.2)%% chance to drop an additional Anarchy Scarab", Minion, 23),
            ("#% chance to drop an additional Torment Scarab", "(1.6-3.2)%% chance to drop an additional Torment Scarab", Minion, 23),
            ("#% chance to drop an additional Ambush Scarab", "(1.6-3.2)%% chance to drop an additional Ambush Scarab", Minion, 32),
            ("#% chance to drop an additional Domination Scarab", "(1.6-3.2)%% chance to drop an additional Domination Scarab", Minion, 30),
            ("#% chance to drop an additional Reliquary Scarab", "(1.6-3.2)%% chance to drop an additional Reliquary Scarab", Minion, 15),
            ("#% chance to drop an additional Miscellaneous Scarab", "(1.6-3.2)%% chance to drop an additional Miscellaneous Scarab", Minion, 15),
            ("#% chance to drop an additional Divination Card which rewards Currency", "(1.6-3.2)%% chance to drop an additional Divination Card which rewards Currency", Minion, 45),
            ("#% chance to drop an additional Divination Card which rewards League Currency", "(1.6-3.2)%% chance to drop an additional Divination Card which rewards League Currency", Minion, 55),
            ("#% chance to drop an additional Divination Card which rewards Basic Currency", "(1.6-3.2)%% chance to drop an additional Divination Card which rewards Basic Currency", Minion, 10),
            ("#% chance to drop an additional Divination Card which rewards Exotic Currency", "(1.6-3.2)%% chance to drop an additional Divination Card which rewards Exotic Currency", Minion, 35),
            ("#% chance to drop an additional Divination Card which rewards a Unique Item", "(1.6-3.2)%% chance to drop an additional Divination Card which rewards a Unique Item", Minion, 18),
            ("#% chance to drop an additional Divination Card which rewards a Unique Weapon", "(1.6-3.2)%% chance to drop an additional Divination Card which rewards a Unique Weapon", Minion, 15),
            ("#% chance to drop an additional Divination Card which rewards a Unique Armour", "(1.6-3.2)%% chance to drop an additional Divination Card which rewards a Unique Armour", Minion, 15),
            ("#% chance to drop an additional Divination Card which rewards Unique Jewellery", "(1.6-3.2)%% chance to drop an additional Divination Card which rewards Unique Jewellery", Minion, 22),
            ("#% chance to drop an additional Divination Card which rewards a Corrupted Unique Item", "(1.6-3.2)%% chance to drop an additional Divination Card which rewards a Corrupted Unique Item", Minion, 10),
            ("#% chance to drop an additional Divination Card which rewards Gems", "(1.6-3.2)%% chance to drop an additional Divination Card which rewards Gems", Minion, 8),
            ("#% chance to drop an additional Divination Card which rewards Levelled Gems", "(1.6-3.2)%% chance to drop an additional Divination Card which rewards Levelled Gems", Minion, 12),
            ("#% chance to drop an additional Divination Card which rewards Quality Gems", "(1.6-3.2)%% chance to drop an additional Divination Card which rewards Quality Gems", Minion, 15),
            ("#% chance to drop an additional Divination Card which rewards a Map", "(1.6-3.2)%% chance to drop an additional Divination Card which rewards a Map", Minion, 8),
            ("#% chance to drop an additional Divination Card which rewards a Unique Map", "(1.6-3.2)%% chance to drop an additional Divination Card which rewards a Unique Map", Minion, 15),
            ("#% chance to drop an additional Divination Card which rewards other Divination Cards", "(1.6-3.2)%% chance to drop an additional Divination Card which rewards other Divination Cards", Minion, 10),
            ("#% chance to drop an additional Divination Card which rewards a Corrupted Item", "(1.6-3.2)%% chance to drop an additional Divination Card which rewards a Corrupted Item", Minion, 3),
            ("Final Boss drops # additional Divine Orbs", "Final Boss drops (2-4) additional Divine Orbs", Boss, 100),
            ("Final Boss drops # additional Ancient Orbs", "Final Boss drops (2-4) additional Ancient Orbs", Boss, 75),
            ("Final Boss drops # additional Exalted Orbs", "Final Boss drops (2-4) additional Exalted Orbs", Boss, 50),
            ("Final Boss drops # additional Chaos Orbs", "Final Boss drops (2-4) additional Chaos Orbs", Boss, 20),
            ("Final Boss drops # additional Orbs of Annulment", "Final Boss drops (2-4) additional Orbs of Annulment", Boss, 35),
            ("Final Boss drops # additional Vaal Orbs", "Final Boss drops (2-4) additional Vaal Orbs", Boss, 25),
            ("Final Boss drops # additional Regal Orbs", "Final Boss drops (2-4) additional Regal Orbs", Boss, 15),
            ("Final Boss drops # additional Gemcutter's Prisms", "Final Boss drops (2-4) additional Gemcutter's Prisms", Boss, 18),
            ("Final Boss drops # additional Grand Eldritch Ichors", "Final Boss drops (2-4) additional Grand Eldritch Ichors", Boss, 40),
            ("Final Boss drops # additional Greater Eldritch Ichors", "Final Boss drops (2-4) additional Greater Eldritch Ichors", Boss, 20),
            ("Final Boss drops # additional Lesser Eldritch Ichors", "Final Boss drops (2-4) additional Lesser Eldritch Ichors", Boss, 8),
            ("Final Boss drops # additional Grand Eldritch Embers", "Final Boss drops (2-4) additional Grand Eldritch Embers", Boss, 40),
            ("Final Boss drops # additional Greater Eldritch Embers", "Final Boss drops (2-4) additional Greater Eldritch Embers", Boss, 20),
            ("Final Boss drops # additional Lesser Eldritch Embers", "Final Boss drops (2-4) additional Lesser Eldritch Embers", Boss, 9),
            ("Final Boss drops # additional Eldritch Exalted Orbs", "Final Boss drops (2-4) additional Eldritch Exalted Orbs", Boss, 36),
            ("Final Boss drops # additional Eldritch Orbs of Annulment", "Final Boss drops (2-4) additional Eldritch Orbs of Annulment", Boss, 30),
            ("Final Boss drops # additional Orbs of Fusing", "Final Boss drops (2-4) additional Orbs of Fusing", Boss, 10),
            ("Final Boss drops # additional Jeweller's Orbs", "Final Boss drops (2-4) additional Jeweller's Orbs", Boss, 5),
            ("Final Boss drops # additional Chromatic Orbs", "Final Boss drops (2-4) additional Chromatic Orbs", Boss, 4),
            ("Final Boss drops # additional Orbs of Scouring", "Final Boss drops (2-4) additional Orbs of Scouring", Boss, 6),
            ("Final Boss drops # additional Orbs of Binding", "Final Boss drops (2-4) additional Orbs of Binding", Boss, 5),
            ("Final Boss drops # additional Orbs of Horizons", "Final Boss drops (2-4) additional Orbs of Horizons", Boss, 6),
            ("Final Boss drops # additional Blessed Orbs", "Final Boss drops (2-4) additional Blessed Orbs", Boss, 3),
            ("Final Boss drops # additional Orbs of Regret", "Final Boss drops (2-4) additional Orbs of Regret", Boss, 8),
            ("Final Boss drops # additional Orbs of Unmaking", "Final Boss drops (2-4) additional Orbs of Unmaking", Boss, 5),
            ("Final Boss drops # additional Glassblower's Baubles", "Final Boss drops (2-4) additional Glassblower's Baubles", Boss, 3),
            ("Final Boss drops # additional Cartographer's Chisels", "Final Boss drops (2-4) additional Cartographer's Chisels", Boss, 8),
            ("Final Boss drops # additional Enkindling Orbs", "Final Boss drops (2-4) additional Enkindling Orbs", Boss, 4),
            ("Final Boss drops # additional Instilling Orbs", "Final Boss drops (2-4) additional Instilling Orbs", Boss, 4),
            ("Final Boss drops # additional Orbs of Alteration", "Final Boss drops (2-4) additional Orbs of Alteration", Boss, 2),
            ("Final Boss drops # additional Delirium Scarabs", "Final Boss drops (2-4) additional Delirium Scarabs", Boss, 22),
            ("Final Boss drops # additional Breach Scarabs", "Final Boss drops (2-4) additional Breach Scarabs", Boss, 25),
            ("Final Boss drops # additional Legion Scarabs", "Final Boss drops (2-4) additional Legion Scarabs", Boss, 26),
            ("Final Boss drops # additional Blight Scarabs", "Final Boss drops (2-4) additional Blight Scarabs", Boss, 22),
            ("Final Boss drops # additional Expedition Scarabs", "Final Boss drops (2-4) additional Expedition Scarabs", Boss, 22),
            ("Final Boss drops # additional Harvest Scarabs", "Final Boss drops (2-4) additional Harvest Scarabs", Boss, 22),
            ("Final Boss drops # additional Ultimatum Scarabs", "Final Boss drops (2-4) additional Ultimatum Scarabs", Boss, 23),
            ("Final Boss drops # additional Betrayal Scarabs", "Final Boss drops (2-4) additional Betrayal Scarabs", Boss, 23),
            ("Final Boss drops # additional Ritual Scarabs", "Final Boss drops (2-4) additional Ritual Scarabs", Boss, 20),
            ("Final Boss drops # additional Abyss Scarabs", "Final Boss drops (2-4) additional Abyss Scarabs", Boss, 22),
            ("Final Boss drops # additional Bestiary Scarabs", "Final Boss drops (2-4) additional Bestiary Scarabs", Boss, 22),
            ("Final Boss drops # additional Incursion Scarabs", "Final Boss drops (2-4) additional Incursion Scarabs", Boss, 23),
            ("Final Boss drops # additional Harbinger Scarabs", "Final Boss drops (2-4) additional Harbinger Scarabs", Boss, 18),
            ("Final Boss drops # additional Sulphite Scarabs", "Final Boss drops (2-4) additional Sulphite Scarabs", Boss, 22),
            ("Final Boss drops # additional Influence Scarabs", "Final Boss drops (2-4) additional Influence Scarabs", Boss, 20),
            ("Final Boss drops # additional Cartography Scarabs", "Final Boss drops (2-4) additional Cartography Scarabs", Boss, 22),
            ("Final Boss drops # additional Divination Scarabs", "Final Boss drops (2-4) additional Divination Scarabs", Boss, 30),
            ("Final Boss drops # additional Essence Scarabs", "Final Boss drops (2-4) additional Essence Scarabs", Boss, 18),
            ("Final Boss drops # additional Beyond Scarabs", "Final Boss drops (2-4) additional Beyond Scarabs", Boss, 22),
            ("Final Boss drops # additional Anarchy Scarabs", "Final Boss drops (2-4) additional Anarchy Scarabs", Boss, 23),
            ("Final Boss drops # additional Torment Scarabs", "Final Boss drops (2-4) additional Torment Scarabs", Boss, 23),
            ("Final Boss drops # additional Titanic Scarabs", "Final Boss drops (2-4) additional Titanic Scarabs", Boss, 15),
            ("Final Boss drops # additional Kalguuran Scarabs", "Final Boss drops (2-4) additional Kalguuran Scarabs", Boss, 23),
            ("Final Boss drops # additional Ambush Scarabs", "Final Boss drops (2-4) additional Ambush Scarabs", Boss, 32),
            ("Final Boss drops # additional Domination Scarabs", "Final Boss drops (2-4) additional Domination Scarabs", Boss, 30),
            ("Final Boss drops # additional Reliquary Scarabs", "Final Boss drops (2-4) additional Reliquary Scarabs", Boss, 15),
            ("Final Boss drops # additional Miscellaneous Scarabs", "Final Boss drops (2-4) additional Miscellaneous Scarabs", Boss, 15),
            ("Final Boss drops # additional Divination Cards which reward Currency", "Final Boss drops (2-4) additional Divination Cards which reward Currency", Boss, 45),
            ("Final Boss drops # additional Divination Cards which reward League Currency", "Final Boss drops (2-4) additional Divination Cards which reward League Currency", Boss, 55),
            ("Final Boss drops # additional Divination Cards which reward Basic Currency", "Final Boss drops (2-4) additional Divination Cards which reward Basic Currency", Boss, 10),
            ("Final Boss drops # additional Divination Cards which reward Exotic Currency", "Final Boss drops (2-4) additional Divination Cards which reward Exotic Currency", Boss, 35),
            ("Final Boss drops # additional Divination Cards which reward a Unique Item", "Final Boss drops (2-4) additional Divination Cards which reward a Unique Item", Boss, 18),
            ("Final Boss drops # additional Divination Cards which reward a Unique Weapon", "Final Boss drops (2-4) additional Divination Cards which reward a Unique Weapon", Boss, 15),
            ("Final Boss drops # additional Divination Cards which reward a Unique Armour", "Final Boss drops (2-4) additional Divination Cards which reward a Unique Armour", Boss, 15),
            ("Final Boss drops # additional Divination Cards which reward Unique Jewellery", "Final Boss drops (2-4) additional Divination Cards which reward Unique Jewellery", Boss, 22),
            ("Final Boss drops # additional Divination Cards which reward a Corrupted Unique Item", "Final Boss drops (2-4) additional Divination Cards which reward a Corrupted Unique Item", Boss, 10),
            ("Final Boss drops # additional Divination Cards which reward Gems", "Final Boss drops (2-4) additional Divination Cards which reward Gems", Boss, 8),
            ("Final Boss drops # additional Divination Cards which reward Levelled Gems", "Final Boss drops (2-4) additional Divination Cards which reward Levelled Gems", Boss, 12),
            ("Final Boss drops # additional Divination Cards which reward Quality Gems", "Final Boss drops (2-4) additional Divination Cards which reward Quality Gems", Boss, 15),
            ("Final Boss drops # additional Divination Cards which reward a Map", "Final Boss drops (2-4) additional Divination Cards which reward a Map", Boss, 8),
            ("Final Boss drops # additional Divination Cards which reward a Unique Map", "Final Boss drops (2-4) additional Divination Cards which reward a Unique Map", Boss, 28),
            ("Final Boss drops # additional Divination Cards which reward other Divination Cards", "Final Boss drops (2-4) additional Divination Cards which reward other Divination Cards", Boss, 22),
            ("Final Boss drops # additional Divination Cards which reward a Corrupted Item", "Final Boss drops (2-4) additional Divination Cards which reward a Corrupted Item", Boss, 8),
            ("Basic Currency Items dropped by slain Enemies have #% chance to be Duplicated (15-30)", "Basic Currency Items dropped by slain Enemies have (15-30)%% chance to be Duplicated", Player, 45),
            ("Basic Currency Items dropped by slain Enemies have #% chance to be Duplicated (10-15)", "Basic Currency Items dropped by slain Enemies have (10-15)%% chance to be Duplicated", Player, 30),
            ("Unique Items dropped by slain Enemies have #% chance to be Duplicated", "Unique Items dropped by slain Enemies have (15-30)%% chance to be Duplicated", Player, 28),
            ("Scarabs dropped by slain Enemies have #% chance to be Duplicated", "Scarabs dropped by slain Enemies have (15-30)%% chance to be Duplicated", Player, 60),
            ("Maps dropped by slain Enemies have #% chance to be Duplicated", "Maps dropped by slain Enemies have (15-30)%% chance to be Duplicated", Player, 35),
            ("Divination Cards dropped by slain Enemies have #% chance to be Duplicated", "Divination Cards dropped by slain Enemies have (15-30)%% chance to be Duplicated", Player, 50),
            ("Gems dropped by slain Enemies have #% chance to be Duplicated", "Gems dropped by slain Enemies have (10-15)%% chance to be Duplicated", Player, 10),
            ("#% increased Quantity of Items found in this Area", "(10-20)%% increased Quantity of Items found in this Area", Player, 70),
            ("#% increased Rarity of Items found in this Area", "(15-35)%% increased Rarity of Items found in this Area", Player, 40),
            ("#% increased Experience gain", "(8-12)%% increased Experience gain", Player, 25),
        };
        #endregion
    }
}
